-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 18:09:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eventWebsiteDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventWebsiteDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventWebsiteDatabase` DEFAULT CHARACTER SET utf8 ;
USE `eventWebsiteDatabase` ;

-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`userTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`userTypes` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`userTypes` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `typeName` VARCHAR(50) NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`user` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `emailAddress` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `userTypeID` INT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_usertype_idx` (`userTypeID` ASC),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  CONSTRAINT `fk_usertype`
    FOREIGN KEY (`userTypeID`)
    REFERENCES `eventWebsiteDatabase`.`userTypes` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`superAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`superAdmin` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`superAdmin` (
  `superAdminID` INT NOT NULL,
  PRIMARY KEY (`superAdminID`),
  UNIQUE INDEX `superAdminID_UNIQUE` (`superAdminID` ASC),
  CONSTRAINT `fk_superAdmin_isa_user`
    FOREIGN KEY (`superAdminID`)
    REFERENCES `eventWebsiteDatabase`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`location` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`location` (
  `locationID` INT NOT NULL AUTO_INCREMENT,
  `locationName` VARCHAR(100) NULL,
  `locationLongitude` DECIMAL NULL,
  `locationLatitude` DECIMAL NULL,
  PRIMARY KEY (`locationID`),
  UNIQUE INDEX `locationID_UNIQUE` (`locationID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`university`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`university` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`university` (
  `universityID` INT NOT NULL AUTO_INCREMENT,
  `universityName` VARCHAR(45) NULL,
  `universityDescription` VARCHAR(255) NULL,
  `universityNumStudents` INT NULL,
  `superAdmin_superAdminID` INT NOT NULL,
  `location_locationID` INT NOT NULL,
  PRIMARY KEY (`universityID`, `superAdmin_superAdminID`, `location_locationID`),
  INDEX `fk_university_superAdmin1_idx` (`superAdmin_superAdminID` ASC),
  INDEX `fk_university_location1_idx` (`location_locationID` ASC),
  UNIQUE INDEX `location_locationID_UNIQUE` (`location_locationID` ASC),
  UNIQUE INDEX `superAdmin_superAdminID_UNIQUE` (`superAdmin_superAdminID` ASC),
  CONSTRAINT `fk_university_superAdmin1`
    FOREIGN KEY (`superAdmin_superAdminID`)
    REFERENCES `eventWebsiteDatabase`.`superAdmin` (`superAdminID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_university_location1`
    FOREIGN KEY (`location_locationID`)
    REFERENCES `eventWebsiteDatabase`.`location` (`locationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`admin` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`admin` (
  `adminID` INT NOT NULL,
  `university_universityID` INT NOT NULL,
  `university_superAdmin_superAdminID` INT NOT NULL,
  PRIMARY KEY (`adminID`, `university_universityID`, `university_superAdmin_superAdminID`),
  INDEX `fk_admin_university1_idx` (`university_universityID` ASC, `university_superAdmin_superAdminID` ASC),
  CONSTRAINT `fk_admin_university1`
    FOREIGN KEY (`university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`university` (`universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_isa_user`
    FOREIGN KEY (`adminID`)
    REFERENCES `eventWebsiteDatabase`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`student` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`student` (
  `studentID` INT NOT NULL,
  `university_universityID` INT NOT NULL,
  `university_superAdmin_superAdminID` INT NOT NULL,
  PRIMARY KEY (`studentID`, `university_universityID`, `university_superAdmin_superAdminID`),
  INDEX `fk_student_university1_idx` (`university_universityID` ASC, `university_superAdmin_superAdminID` ASC),
  CONSTRAINT `fk_student_university1`
    FOREIGN KEY (`university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`university` (`universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_isa_user`
    FOREIGN KEY (`studentID`)
    REFERENCES `eventWebsiteDatabase`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`RSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`RSO` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`RSO` (
  `RSOid` INT NOT NULL AUTO_INCREMENT,
  `RSOname` VARCHAR(45) NULL,
  `admin_adminID` INT NOT NULL,
  `admin_university_universityID` INT NOT NULL,
  PRIMARY KEY (`RSOid`, `admin_adminID`, `admin_university_universityID`),
  INDEX `fk_RSO_admin1_idx` (`admin_adminID` ASC, `admin_university_universityID` ASC),
  CONSTRAINT `fk_RSO_admin1`
    FOREIGN KEY (`admin_adminID`)
    REFERENCES `eventWebsiteDatabase`.`admin` (`adminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`event` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`event` (
  `eventID` INT NOT NULL,
  `eventName` VARCHAR(45) NULL,
  `eventDate` DATETIME NULL,
  `eventCategory` VARCHAR(45) NULL,
  `eventDescription` VARCHAR(255) NULL,
  `eventContactPhone` INT NULL,
  `eventContactEmail` VARCHAR(255) NULL,
  `location_locationID` INT NOT NULL,
  `RSO_RSOid` INT NOT NULL,
  `RSO_admin_adminID` INT NOT NULL,
  `RSO_admin_university_universityID` INT NOT NULL,
  PRIMARY KEY (`eventID`, `location_locationID`, `RSO_RSOid`, `RSO_admin_adminID`, `RSO_admin_university_universityID`),
  INDEX `fk_event_location1_idx` (`location_locationID` ASC),
  INDEX `fk_event_RSO1_idx` (`RSO_RSOid` ASC, `RSO_admin_adminID` ASC, `RSO_admin_university_universityID` ASC),
  CONSTRAINT `fk_event_location1`
    FOREIGN KEY (`location_locationID`)
    REFERENCES `eventWebsiteDatabase`.`location` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_RSO1`
    FOREIGN KEY (`RSO_RSOid` , `RSO_admin_adminID` , `RSO_admin_university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`RSO` (`RSOid` , `admin_adminID` , `admin_university_universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`RSO_has_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`RSO_has_student` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`RSO_has_student` (
  `RSO_RSOid` INT NOT NULL,
  `RSO_admin_adminID` INT NOT NULL,
  `RSO_admin_university_universityID` INT NOT NULL,
  `student_studentID` INT NOT NULL,
  `student_university_universityID` INT NOT NULL,
  `student_university_superAdmin_superAdminID` INT NOT NULL,
  PRIMARY KEY (`RSO_RSOid`, `RSO_admin_adminID`, `RSO_admin_university_universityID`, `student_studentID`, `student_university_universityID`, `student_university_superAdmin_superAdminID`),
  INDEX `fk_RSO_has_student_student1_idx` (`student_studentID` ASC, `student_university_universityID` ASC, `student_university_superAdmin_superAdminID` ASC),
  INDEX `fk_RSO_has_student_RSO1_idx` (`RSO_RSOid` ASC, `RSO_admin_adminID` ASC, `RSO_admin_university_universityID` ASC),
  CONSTRAINT `fk_RSO_has_student_RSO1`
    FOREIGN KEY (`RSO_RSOid` , `RSO_admin_adminID` , `RSO_admin_university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`RSO` (`RSOid` , `admin_adminID` , `admin_university_universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RSO_has_student_student1`
    FOREIGN KEY (`student_studentID` , `student_university_universityID` , `student_university_superAdmin_superAdminID`)
    REFERENCES `eventWebsiteDatabase`.`student` (`studentID` , `university_universityID` , `university_superAdmin_superAdminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`university_has_RSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`university_has_RSO` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`university_has_RSO` (
  `university_universityID` INT NOT NULL,
  `university_superAdmin_superAdminID` INT NOT NULL,
  `RSO_RSOid` INT NOT NULL,
  `RSO_admin_adminID` INT NOT NULL,
  `RSO_admin_university_universityID` INT NOT NULL,
  PRIMARY KEY (`university_universityID`, `university_superAdmin_superAdminID`, `RSO_RSOid`, `RSO_admin_adminID`, `RSO_admin_university_universityID`),
  INDEX `fk_university_has_RSO_RSO1_idx` (`RSO_RSOid` ASC, `RSO_admin_adminID` ASC, `RSO_admin_university_universityID` ASC),
  INDEX `fk_university_has_RSO_university1_idx` (`university_universityID` ASC, `university_superAdmin_superAdminID` ASC),
  CONSTRAINT `fk_university_has_RSO_university1`
    FOREIGN KEY (`university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`university` (`universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_university_has_RSO_RSO1`
    FOREIGN KEY (`RSO_RSOid` , `RSO_admin_adminID` , `RSO_admin_university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`RSO` (`RSOid` , `admin_adminID` , `admin_university_universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`event_has_RSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`event_has_RSO` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`event_has_RSO` (
  `event_eventID` INT NOT NULL,
  `event_location_locationID` INT NOT NULL,
  `event_RSO_RSOid` INT NOT NULL,
  `event_RSO_admin_adminID` INT NOT NULL,
  `event_RSO_admin_university_universityID` INT NOT NULL,
  `RSO_RSOid` INT NOT NULL,
  `RSO_admin_adminID` INT NOT NULL,
  `RSO_admin_university_universityID` INT NOT NULL,
  PRIMARY KEY (`event_eventID`, `event_location_locationID`, `event_RSO_RSOid`, `event_RSO_admin_adminID`, `event_RSO_admin_university_universityID`, `RSO_RSOid`, `RSO_admin_adminID`, `RSO_admin_university_universityID`),
  INDEX `fk_event_has_RSO_RSO1_idx` (`RSO_RSOid` ASC, `RSO_admin_adminID` ASC, `RSO_admin_university_universityID` ASC),
  INDEX `fk_event_has_RSO_event1_idx` (`event_eventID` ASC, `event_location_locationID` ASC, `event_RSO_RSOid` ASC, `event_RSO_admin_adminID` ASC, `event_RSO_admin_university_universityID` ASC),
  CONSTRAINT `fk_event_has_RSO_event1`
    FOREIGN KEY (`event_eventID` , `event_location_locationID` , `event_RSO_RSOid` , `event_RSO_admin_adminID` , `event_RSO_admin_university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`event` (`eventID` , `location_locationID` , `RSO_RSOid` , `RSO_admin_adminID` , `RSO_admin_university_universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_RSO_RSO1`
    FOREIGN KEY (`RSO_RSOid` , `RSO_admin_adminID` , `RSO_admin_university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`RSO` (`RSOid` , `admin_adminID` , `admin_university_universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventWebsiteDatabase`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventWebsiteDatabase`.`comments` ;

CREATE TABLE IF NOT EXISTS `eventWebsiteDatabase`.`comments` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(140) NULL,
  `datePosted` DATETIME NULL,
  `event_eventID` INT NOT NULL,
  `event_location_locationID` INT NOT NULL,
  `event_RSO_RSOid` INT NOT NULL,
  `event_RSO_admin_adminID` INT NOT NULL,
  `event_RSO_admin_university_universityID` INT NOT NULL,
  PRIMARY KEY (`commentID`, `event_eventID`, `event_location_locationID`, `event_RSO_RSOid`, `event_RSO_admin_adminID`, `event_RSO_admin_university_universityID`),
  INDEX `fk_comments_event1_idx` (`event_eventID` ASC, `event_location_locationID` ASC, `event_RSO_RSOid` ASC, `event_RSO_admin_adminID` ASC, `event_RSO_admin_university_universityID` ASC),
  CONSTRAINT `fk_comments_event1`
    FOREIGN KEY (`event_eventID` , `event_location_locationID` , `event_RSO_RSOid` , `event_RSO_admin_adminID` , `event_RSO_admin_university_universityID`)
    REFERENCES `eventWebsiteDatabase`.`event` (`eventID` , `location_locationID` , `RSO_RSOid` , `RSO_admin_adminID` , `RSO_admin_university_universityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO dbuser;
 DROP USER dbuser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'dbuser' IDENTIFIED BY '&z47JGdzgrT*^uG';

GRANT SELECT, INSERT, TRIGGER ON TABLE `eventWebsiteDatabase`.* TO 'dbuser';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `eventWebsiteDatabase`.* TO 'dbuser';
GRANT ALL ON `eventWebsiteDatabase`.* TO 'dbuser';
GRANT EXECUTE ON ROUTINE `eventWebsiteDatabase`.* TO 'dbuser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
